export interface Event {

    _id: String,
    name: String,
    fromDate: String,
    toDate: String,
    attendance: Object[],
    seatPickerUrl : String,
    eventLocation : String,
    eventUrl : String,
    clanTracker : String,
    clanPage : String,
    chatLink : String,
    hotelCheckin : Date,
    hotelCheckinTime : String,
    hotelCheckout : Date,
    hotelCheckoutTime : String,
    hotelAddress : String,
    hotelNumber :String,
    hotelName : String,
    jerseySizeChart : String,
    jerseyPaymentLink : String,
    jerseyDesignLink : String,
    mealAddress : String,
    mealName : String,
    mealTime : String,
    mealDate : Date,
    showJersey : Boolean,
    showQuiz : Boolean,
    showComps : Boolean,
    showSeating : Boolean,
    showMeal : Boolean

}
